### ISSUE TITLE
windows8/8.1表記

### ISSUE THREAD

**Issue by 2nd-junkey** [kurone-kito/setup.windows#2]
8と8.1が一纏めになってるのと、それを81で処理しているのはわざと？

**Comment by kurone-kito** [comment]
Windows 8はVistaさんとかと同様、既にサポート終了しています。
そのため本プロジェクトでも、下記のみ対応予定です。

- Windows 7
- Windows 8.1
- Windows 10

8 → 8.1 対応バッチを実装するのもアリかもしれませんが、ストア依存なのでコマンドから呼ぶの難しいのと、使う機会あまり無さそう、というのが正直なところです。
（それよりもWindows10 v1511→1809更新の自動化の方が、使う機会ありそう）

**Comment by 2nd-junkey** [comment]
了解です。
(windows10 v1511→1809はもう入れ直しでいいのでは感)
ちなみにコマンド引数を8.1ではなく81にしているのには理由がありますのん？

**Comment by kurone-kito** [comment]
@2nd-junkey  [Vagrant box](https://app.vagrantup.com/boxes/search)においてドットを付記しないのが慣習のようで、私もそれに従って __81__ と表記していました。

、、が、私個人にそういう宗派はないので直しましょう。

**Comment by kurone-kito** [comment]
#5 で直しましたので、こちらは一旦Closeしますね。。
またIssue投げてくれると嬉しいです😌
